import type { CardArchetype, CardEffect, CardFamily, CardSides } from "@/core/types";
import { ADVENTURE_REWARD_ARCHETYPES } from "@/core/config/adventureRewards";
import { getNeutralCardArtSrc } from "@/core/config/cardArt";

function draftCard(options: {
  id: string;
  name: string;
  sides: CardSides;
  family: CardFamily;
  accent: string;
  artSrc?: string;
  effects?: CardEffect[];
}): CardArchetype {
  return {
    id: options.id,
    name: options.name,
    sides: options.sides,
    family: options.family,
    accent: options.accent,
    artSrc: options.artSrc ?? getNeutralCardArtSrc(options.family),
    rarity: "common",
    sourceType: "draft",
    baseArchetypeId: null,
    effects: options.effects ?? [],
  };
}

export const CARD_ARCHETYPES: ReadonlyArray<CardArchetype> = [
  draftCard({
    id: "sapling",
    name: "Floramie toxique",
    sides: { top: 2, right: 5, bottom: 4, left: 1 },
    family: "familiar",
    accent: "sprout",
    effects: [{ trigger: "on-play", kind: "gain-shield", amount: 1, condition: "adjacent-ally" }],
  }),
  draftCard({
    id: "badger",
    name: "Poney runique",
    sides: { top: 5, right: 3, bottom: 2, left: 2 },
    family: "familiar",
    accent: "earth",
    effects: [{ trigger: "on-play", kind: "gain-shield", amount: 2, condition: "corner" }],
  }),
  draftCard({
    id: "heron",
    name: "Oiselle aubeplume",
    sides: { top: 4, right: 3, bottom: 2, left: 3 },
    family: "familiar",
    accent: "mist",
    effects: [{ trigger: "on-flip", kind: "draw-next-turn", amount: 1, minFlips: 1, requiredFamilyCount: 2, scaleWithFamilyCount: true, maxScale: 2 }],
  }),
  draftCard({
    id: "foxfire",
    name: "Requin runefer",
    sides: { top: 3, right: 2, bottom: 5, left: 2 },
    family: "familiar",
    accent: "ember",
    effects: [{ trigger: "on-flip", kind: "gain-shield", amount: 1, minFlips: 1, requiredFamilyCount: 3, scaleWithFamilyCount: true, maxScale: 2 }],
  }),
  draftCard({
    id: "mole",
    name: "Ecureuil mineur",
    sides: { top: 5, right: 2, bottom: 2, left: 3 },
    family: "familiar",
    accent: "stone",
    effects: [{ trigger: "on-play", kind: "boost-self", amount: 1, directions: "weakest", condition: "adjacent-ally" }],
  }),
  draftCard({
    id: "stag",
    name: "Herisson lumisylve",
    sides: { top: 2, right: 2, bottom: 5, left: 3 },
    family: "familiar",
    accent: "grove",
    effects: [{ trigger: "on-play", kind: "draw-next-turn", amount: 1, condition: "center" }],
  }),
  draftCard({
    id: "owl",
    name: "Chaton des ronces",
    sides: { top: 3, right: 4, bottom: 2, left: 3 },
    family: "familiar",
    accent: "glow",
    effects: [{ trigger: "on-play", kind: "gain-shield", amount: 1, condition: "center" }],
  }),

  draftCard({
    id: "ember-imp",
    name: "Diablotin braise",
    sides: { top: 2, right: 5, bottom: 2, left: 3 },
    family: "demon",
    accent: "ember",
    effects: [{ trigger: "on-flip", kind: "deal-damage", amount: 1, minFlips: 1 }],
  }),
  draftCard({
    id: "hornling",
    name: "Cornu farceur",
    sides: { top: 4, right: 2, bottom: 4, left: 2 },
    family: "demon",
    accent: "demon",
    effects: [{ trigger: "on-play", kind: "deal-damage", amount: 1, condition: "adjacent-enemy" }],
  }),
  draftCard({
    id: "ash-whisper",
    name: "Murmure de cendre",
    sides: { top: 2, right: 3, bottom: 5, left: 2 },
    family: "demon",
    accent: "ember",
    effects: [{ trigger: "on-flip", kind: "draw-next-turn", amount: 1, minFlips: 1 }],
  }),
  draftCard({
    id: "pact-sprite",
    name: "Lutin a pacte",
    sides: { top: 3, right: 2, bottom: 2, left: 5 },
    family: "demon",
    accent: "demon",
    effects: [{ trigger: "on-play", kind: "boost-self", amount: 1, directions: "strongest", condition: "adjacent-enemy" }],
  }),
  draftCard({
    id: "little-abyss",
    name: "Petit abysse",
    sides: { top: 5, right: 2, bottom: 3, left: 2 },
    family: "demon",
    accent: "void",
    effects: [{ trigger: "on-play", kind: "deal-damage", amount: 1, condition: "behind-on-board" }],
  }),
  draftCard({
    id: "cinder-grin",
    name: "Sourire de suie",
    sides: { top: 1, right: 5, bottom: 3, left: 3 },
    family: "demon",
    accent: "shadow",
    effects: [{ trigger: "on-flip", kind: "deal-damage", amount: 2, minFlips: 2, requiredFamilyCount: 3, scaleWithFamilyCount: true, maxScale: 2 }],
  }),
  draftCard({
    id: "brimstone-tot",
    name: "Bambin soufre",
    sides: { top: 4, right: 1, bottom: 3, left: 4 },
    family: "demon",
    accent: "ember",
    effects: [{ trigger: "on-play", kind: "deal-damage", amount: 1, condition: "center" }],
  }),

  draftCard({
    id: "field-knight",
    name: "Chevaliere des champs",
    sides: { top: 4, right: 2, bottom: 4, left: 2 },
    family: "human",
    accent: "steel",
    effects: [{ trigger: "on-play", kind: "gain-shield", amount: 2, requiredFamilyCount: 2, scaleWithFamilyCount: true, maxScale: 2 }],
  }),
  draftCard({
    id: "rune-mage",
    name: "Mage des runes",
    sides: { top: 2, right: 5, bottom: 2, left: 3 },
    family: "human",
    accent: "mist",
    effects: [{ trigger: "on-play", kind: "draw-next-turn", amount: 1 }],
  }),
  draftCard({
    id: "path-ranger",
    name: "Rodeuse du sentier",
    sides: { top: 5, right: 2, bottom: 2, left: 3 },
    family: "human",
    accent: "grove",
    effects: [{ trigger: "on-play", kind: "boost-self", amount: 1, directions: "weakest", condition: "adjacent-ally" }],
  }),
  draftCard({
    id: "quiet-monk",
    name: "Moine du seuil",
    sides: { top: 3, right: 3, bottom: 3, left: 3 },
    family: "human",
    accent: "sun",
    effects: [{ trigger: "on-play", kind: "gain-shield", amount: 1, condition: "center" }],
  }),
  draftCard({
    id: "gate-thief",
    name: "Voleuse des portes",
    sides: { top: 2, right: 4, bottom: 2, left: 4 },
    family: "human",
    accent: "shadow",
    effects: [{ trigger: "on-flip", kind: "draw-next-turn", amount: 1, minFlips: 1 }],
  }),
  draftCard({
    id: "banner-squire",
    name: "Ecuyere banniere",
    sides: { top: 4, right: 3, bottom: 3, left: 2 },
    family: "human",
    accent: "steel",
    effects: [{ trigger: "on-play", kind: "gain-shield", amount: 1, condition: "adjacent-ally", requiredFamilyCount: 2, scaleWithFamilyCount: true, maxScale: 2 }],
  }),
  draftCard({
    id: "hearth-archer",
    name: "Archer du foyer",
    sides: { top: 3, right: 4, bottom: 1, left: 4 },
    family: "human",
    accent: "sun",
    effects: [{ trigger: "on-flip", kind: "deal-damage", amount: 1, minFlips: 1 }],
  }),

  draftCard({
    id: "clock-sentinel",
    name: "Sentinelle d'horloge",
    sides: { top: 5, right: 2, bottom: 3, left: 2 },
    family: "automaton",
    accent: "brass",
    effects: [{ trigger: "on-play", kind: "gain-shield", amount: 2, condition: "corner" }],
  }),
  draftCard({
    id: "brass-rook",
    name: "Tour de laiton",
    sides: { top: 2, right: 4, bottom: 2, left: 4 },
    family: "automaton",
    accent: "brass",
    effects: [{ trigger: "on-play", kind: "boost-self", amount: 1, directions: "weakest", condition: "corner", requiredFamilyCount: 2, scaleWithFamilyCount: true, maxScale: 2 }],
  }),
  draftCard({
    id: "gear-monk",
    name: "Moine engrene",
    sides: { top: 3, right: 3, bottom: 4, left: 2 },
    family: "automaton",
    accent: "steel",
    effects: [{ trigger: "on-play", kind: "gain-shield", amount: 1, condition: "adjacent-ally" }],
  }),
  draftCard({
    id: "tin-oracle",
    name: "Oracle de fer-blanc",
    sides: { top: 2, right: 5, bottom: 3, left: 2 },
    family: "automaton",
    accent: "arcane",
    effects: [{ trigger: "on-play", kind: "draw-next-turn", amount: 1, condition: "corner", requiredFamilyCount: 2, scaleWithFamilyCount: true, maxScale: 2 }],
  }),
  draftCard({
    id: "copper-beetle",
    name: "Scarabee cuivre",
    sides: { top: 4, right: 2, bottom: 2, left: 4 },
    family: "automaton",
    accent: "brass",
    effects: [{ trigger: "on-play", kind: "gain-shield", amount: 1, condition: "center" }],
  }),
  draftCard({
    id: "glass-warden",
    name: "Gardien de verre",
    sides: { top: 3, right: 4, bottom: 3, left: 2 },
    family: "automaton",
    accent: "mist",
    effects: [{ trigger: "on-flip", kind: "gain-shield", amount: 1, minFlips: 1 }],
  }),
  draftCard({
    id: "spring-knave",
    name: "Valet ressort",
    sides: { top: 2, right: 3, bottom: 5, left: 2 },
    family: "automaton",
    accent: "steel",
    effects: [{ trigger: "on-play", kind: "boost-self", amount: 1, directions: "strongest", condition: "behind-on-board" }],
  }),

  draftCard({
    id: "grave-child",
    name: "Enfant des tombes",
    sides: { top: 2, right: 2, bottom: 5, left: 3 },
    family: "revenant",
    accent: "shadow",
    effects: [{ trigger: "on-play", kind: "draw-next-turn", amount: 1, condition: "behind-on-board", requiredFamilyCount: 2, scaleWithFamilyCount: true, maxScale: 2 }],
  }),
  draftCard({
    id: "lantern-shade",
    name: "Ombre a lanterne",
    sides: { top: 4, right: 2, bottom: 3, left: 3 },
    family: "revenant",
    accent: "glow",
    effects: [{ trigger: "on-play", kind: "gain-shield", amount: 2, condition: "behind-on-board" }],
  }),
  draftCard({
    id: "bone-choir",
    name: "Choeur d'os",
    sides: { top: 3, right: 4, bottom: 2, left: 3 },
    family: "revenant",
    accent: "mist",
    effects: [{ trigger: "on-flip", kind: "gain-shield", amount: 1, minFlips: 1 }],
  }),
  draftCard({
    id: "widow-knight",
    name: "Chevalier veuf",
    sides: { top: 2, right: 3, bottom: 4, left: 3 },
    family: "revenant",
    accent: "shadow",
    effects: [{ trigger: "on-flip", kind: "deal-damage", amount: 1, minFlips: 1 }],
  }),
  draftCard({
    id: "moth-ghost",
    name: "Fantome phalene",
    sides: { top: 5, right: 1, bottom: 3, left: 3 },
    family: "revenant",
    accent: "glow",
    effects: [{ trigger: "on-play", kind: "boost-self", amount: 1, directions: "weakest", condition: "behind-on-board" }],
  }),
  draftCard({
    id: "hollow-page",
    name: "Page creux",
    sides: { top: 3, right: 3, bottom: 1, left: 5 },
    family: "revenant",
    accent: "shadow",
    effects: [{ trigger: "on-play", kind: "deal-damage", amount: 1, condition: "behind-on-board" }],
  }),
  draftCard({
    id: "veil-duelist",
    name: "Duelliste voile",
    sides: { top: 4, right: 4, bottom: 2, left: 2 },
    family: "revenant",
    accent: "mist",
    effects: [{ trigger: "on-flip", kind: "draw-next-turn", amount: 1, minFlips: 1 }],
  }),

  draftCard({
    id: "star-witch",
    name: "Sorciere d'etoiles",
    sides: { top: 2, right: 4, bottom: 4, left: 2 },
    family: "arcane",
    accent: "arcane",
    effects: [{ trigger: "on-play", kind: "boost-self", amount: 1, directions: "weakest", condition: "center", requiredFamilyCount: 2, scaleWithFamilyCount: true, maxScale: 2 }],
  }),
  draftCard({
    id: "rune-adept",
    name: "Adepte sigillaire",
    sides: { top: 4, right: 3, bottom: 2, left: 3 },
    family: "arcane",
    accent: "arcane",
    effects: [{ trigger: "on-play", kind: "draw-next-turn", amount: 1, condition: "center" }],
  }),
  draftCard({
    id: "mirror-novice",
    name: "Novice miroir",
    sides: { top: 3, right: 2, bottom: 5, left: 2 },
    family: "arcane",
    accent: "mist",
    effects: [{ trigger: "on-flip", kind: "draw-next-turn", amount: 1, minFlips: 1 }],
  }),
  draftCard({
    id: "moon-scribe",
    name: "Scribe lunaire",
    sides: { top: 5, right: 1, bottom: 2, left: 4 },
    family: "arcane",
    accent: "arcane",
    effects: [{ trigger: "on-play", kind: "boost-self", amount: 1, directions: "strongest", condition: "center" }],
  }),
  draftCard({
    id: "glass-oracle",
    name: "Oracle de verre",
    sides: { top: 1, right: 5, bottom: 4, left: 2 },
    family: "arcane",
    accent: "mist",
    effects: [{ trigger: "on-flip", kind: "deal-damage", amount: 1, minFlips: 1 }],
  }),
  draftCard({
    id: "wandering-glyph",
    name: "Glyphe errant",
    sides: { top: 3, right: 3, bottom: 3, left: 3 },
    family: "arcane",
    accent: "glow",
    effects: [{ trigger: "on-play", kind: "gain-shield", amount: 1, condition: "center" }],
  }),
  draftCard({
    id: "blue-comet",
    name: "Comete bleue",
    sides: { top: 4, right: 2, bottom: 2, left: 4 },
    family: "arcane",
    accent: "arcane",
    effects: [{ trigger: "on-play", kind: "draw-next-turn", amount: 1, condition: "adjacent-ally", requiredFamilyCount: 2, scaleWithFamilyCount: true, maxScale: 2 }],
  }),

  ...ADVENTURE_REWARD_ARCHETYPES,
];

export const CARD_ARCHETYPE_LOOKUP = Object.fromEntries(
  CARD_ARCHETYPES.map((card) => [card.id, card]),
) as Record<string, CardArchetype>;
