import type {
  AdventureConfig,
  AdventureCharmConfig,
  AdventureEnemyConfig,
  AdventureRewardConfig,
  BotTrainingConfig,
  MatchConfig,
} from "@/core/types";

export const POSITION_WEIGHTS = [
  [7, 4, 7],
  [4, 5, 4],
  [7, 4, 7],
] as const;

export const GAME_CONFIG: MatchConfig = {
  boardSize: 3,
  cardsPerTurn: 5,
  turnMana: 4,
  maxCardsPerMove: 3,
  firstPlayerFirstTurnShieldBonus: 2,
  secondPlayerFirstTurnDrawBonus: 0,
  secondPlayerFirstTurnShieldBonus: 0,
  aiDelayMs: 1200,
  defaultSeed: 12,
  startingPlayer: "player",
  championStartingHealth: 20,
  roundDamagePerControlledCard: 2,
  maxShieldPerPlayer: 6,
  maxNextTurnDrawBonus: 3,
  maxDirectDamagePerMove: 4,
  maxCardSideValue: 8,
};

export const ADVENTURE_CONFIG: AdventureConfig = {
  draftOfferSize: 14,
  draftPickCount: 7,
  depthCount: 8,
  laneCount: 5,
  minStartingNodes: 2,
  maxStartingNodes: 3,
  minNodesPerDepth: 2,
  maxNodesPerDepth: 3,
  maxLaneDrift: 1,
  extraConnectionChance: 0.16,
  combatWeight: 28,
  eliteWeight: 7,
  shopWeight: 20,
  chestWeight: 21,
  restWeight: 24,
  preBossCombatWeight: 13,
  preBossEliteWeight: 6,
  preBossShopWeight: 25,
  preBossChestWeight: 25,
  preBossRestWeight: 31,
};

export const ADVENTURE_REWARD_CONFIG: AdventureRewardConfig = {
  offerSize: 4,
  normalCommonWeight: 62,
  normalUncommonWeight: 35,
  normalRareWeight: 3,
  eliteCommonWeight: 50,
  eliteUncommonWeight: 36,
  eliteRareWeight: 14,
  treasureCommonWeight: 38,
  treasureUncommonWeight: 42,
  treasureRareWeight: 20,
  rareUnlockOfferIndex: 3,
  maxRareOffersPerRun: 3,
  maxUncommonOffersPerRun: 6,
  firstGuaranteedUncommonOfferIndex: 1,
  secondGuaranteedUncommonOfferIndex: 3,
};

export const ADVENTURE_REWARD_FIT_CONFIG = {
  finalistCount: 5,
  sameFamilyScore: 16,
  hybridFamilyScore: 7,
  familyPresenceScore: 5,
  familyCardScore: 1.4,
  maxFamilyCardScore: 10,
  missingRoleScore: 11,
  attackerScore: 4.5,
  payoffScore: 4.5,
  payoffConnectorScore: 5,
  attackerAnchorScore: 3.5,
  firstCopyScore: 2,
  duplicatePenalty: 4,
  uncommonScore: 3,
  rareScore: 5,
  activeFamilyConditionScore: 7,
  inactiveFamilyConditionPenalty: 5,
  activeHybridConditionScore: 9,
  inactiveHybridConditionPenalty: 4,
  adjacentSetupScore: 2.5,
  positionSetupScore: 2.5,
  onFlipAttackerScore: 2.5,
  drawScore: 1.3,
  shieldScore: 1.2,
  boostScore: 1.4,
} as const;

export const ADVENTURE_BOT_WEIGHT_LIMITS = {
  specialCardValue: { min: 0, max: 18 },
  deckTrimValue: { min: 0, max: 14 },
  eliteRouteBias: { min: -8, max: 8 },
  restRouteBias: { min: 0, max: 12 },
  forgeRouteBias: { min: 0, max: 12 },
  treasureRouteBias: { min: 0, max: 12 },
  branchingRouteBias: { min: 0, max: 10 },
  riskTolerance: { min: -4, max: 8 },
  aggressionPlanBias: { min: -12, max: 18 },
  controlPlanBias: { min: -12, max: 18 },
  tempoPlanBias: { min: -12, max: 18 },
  fusionPlanBias: { min: -12, max: 18 },
  precisionPlanBias: { min: -12, max: 18 },
  uncommonCardBias: { min: -4, max: 10 },
  rareCardBias: { min: -4, max: 12 },
  charmSynergyBias: { min: -4, max: 14 },
  duplicateCardPenalty: { min: 0, max: 10 },
  enemyProfileRespect: { min: 0, max: 10 },
} as const;

export const ADVENTURE_CHARM_CONFIG: AdventureCharmConfig = {
  offerSize: 3,
  starterOfferSize: 3,
  chestOfferSize: 3,
  eliteOfferSize: 3,
  eliteDropChance: 0.28,
  chestCommonWeight: 68,
  chestRareWeight: 26,
  chestLegendaryWeight: 6,
  eliteCommonWeight: 42,
  eliteRareWeight: 44,
  eliteLegendaryWeight: 14,
};

export const ADVENTURE_ENEMY_CONFIG: AdventureEnemyConfig = {
  earlyNormalStarterCardCount: 6,
  normalMaxReplacements: 1,
  normalMaxAdds: 0,
  eliteReplacementBonus: 1,
  eliteAddBonus: 1,
  bossReplacementCount: 3,
  bossAddCount: 0,
  playerUpgradePressure: 0.18,
  playerUncommonPressure: 0.3,
  playerRarePressure: 1,
  uncommonUnlockLocation: 4,
  rareUnlockLocation: 7,
  eliteRareUnlockLocation: 8,
  bossRareUnlockLocation: 8,
  earlyNormalCommonWeight: 100,
  earlyNormalUncommonWeight: 0,
  earlyNormalRareWeight: 0,
  midNormalCommonWeight: 92,
  midNormalUncommonWeight: 8,
  midNormalRareWeight: 0,
  lateNormalCommonWeight: 72,
  lateNormalUncommonWeight: 25,
  lateNormalRareWeight: 3,
  earlyEliteCommonWeight: 80,
  earlyEliteUncommonWeight: 20,
  earlyEliteRareWeight: 0,
  lateEliteCommonWeight: 40,
  lateEliteUncommonWeight: 44,
  lateEliteRareWeight: 16,
  bossCommonWeight: 22,
  bossUncommonWeight: 50,
  bossRareWeight: 28,
};

export const BOT_TRAINING_CONFIG: BotTrainingConfig = {
  populationSize: 10,
  eliteCount: 3,
  iterations: 8,
  matchesPerOpponent: 8,
  promotionMatchesPerOpponent: 12,
  initialSigma: 3.5,
  sigmaDecay: 0.84,
  minSigma: 0.45,
  defaultSearchDepth: 2,
  defaultBeamWidth: 10,
  heuristicBaselineBlend: 0.14,
  campaignTrainingRunsPerOpponent: 4,
  campaignPromotionRunsPerOpponent: 6,
  campaignScoreWeight: 0.11,
  promotionMinimumWinRateVsHeuristic: 0.54,
  promotionMinimumWinRateVsChampion: 0.5,
  promotionMinimumAverageHpEdge: 0.1,
  promotionMinimumCampaignScoreVsHeuristic: 24,
  promotionMinimumCampaignScoreVsChampion: 12,
  promotionMinimumBossReachRateVsHeuristic: 0,
  promotionMinimumBossReachRateVsChampion: 0,
};
