import type {
  AdventureConfig,
  AdventureCharmConfig,
  AdventureEnemyConfig,
  AdventureRewardConfig,
  BotTrainingConfig,
  MatchConfig,
} from "@/core/types";

export const POSITION_WEIGHTS = [
  [7, 4, 7],
  [4, 5, 4],
  [7, 4, 7],
] as const;

export const GAME_CONFIG: MatchConfig = {
  boardSize: 3,
  cardsPerTurn: 5,
  turnMana: 3,
  maxCardsPerMove: 3,
  secondPlayerFirstTurnDrawBonus: 2,
  secondPlayerFirstTurnShieldBonus: 1,
  aiDelayMs: 1200,
  defaultSeed: 12,
  startingPlayer: "player",
  championStartingHealth: 24,
  roundDamagePerControlledCard: 1,
  maxShieldPerPlayer: 6,
  maxNextTurnDrawBonus: 2,
  maxDirectDamagePerMove: 4,
  maxCardSideValue: 12,
};

export const ADVENTURE_CONFIG: AdventureConfig = {
  draftOfferSize: 14,
  draftPickCount: 7,
  depthCount: 12,
  laneCount: 5,
  minStartingNodes: 2,
  maxStartingNodes: 3,
  minNodesPerDepth: 2,
  maxNodesPerDepth: 3,
  maxLaneDrift: 1,
  extraConnectionChance: 0.16,
  combatWeight: 54,
  eliteWeight: 16,
  shopWeight: 10,
  chestWeight: 8,
  restWeight: 12,
  preBossCombatWeight: 34,
  preBossEliteWeight: 18,
  preBossShopWeight: 18,
  preBossChestWeight: 10,
  preBossRestWeight: 20,
};

export const ADVENTURE_REWARD_CONFIG: AdventureRewardConfig = {
  offerSize: 3,
  normalCommonWeight: 84,
  normalUncommonWeight: 15,
  normalRareWeight: 1,
  eliteCommonWeight: 70,
  eliteUncommonWeight: 25,
  eliteRareWeight: 5,
  treasureCommonWeight: 62,
  treasureUncommonWeight: 30,
  treasureRareWeight: 8,
  rareUnlockOfferIndex: 3,
  maxRareOffersPerRun: 1,
  maxUncommonOffersPerRun: 3,
  firstGuaranteedUncommonOfferIndex: 4,
  secondGuaranteedUncommonOfferIndex: 7,
};

export const ADVENTURE_CHARM_CONFIG: AdventureCharmConfig = {
  offerSize: 3,
  starterOfferSize: 3,
  chestOfferSize: 3,
  eliteOfferSize: 3,
  eliteDropChance: 0.28,
  chestCommonWeight: 68,
  chestRareWeight: 26,
  chestLegendaryWeight: 6,
  eliteCommonWeight: 42,
  eliteRareWeight: 44,
  eliteLegendaryWeight: 14,
};

export const ADVENTURE_ENEMY_CONFIG: AdventureEnemyConfig = {
  normalMaxReplacements: 5,
  normalMaxAdds: 2,
  eliteReplacementBonus: 2,
  eliteAddBonus: 1,
  bossReplacementCount: 14,
  bossAddCount: 0,
  playerUpgradePressure: 0.5,
  playerUncommonPressure: 0.75,
  playerRarePressure: 1.5,
  uncommonUnlockLocation: 2,
  rareUnlockLocation: 7,
  eliteRareUnlockLocation: 5,
  bossRareUnlockLocation: 10,
  earlyNormalCommonWeight: 100,
  earlyNormalUncommonWeight: 0,
  earlyNormalRareWeight: 0,
  midNormalCommonWeight: 85,
  midNormalUncommonWeight: 15,
  midNormalRareWeight: 0,
  lateNormalCommonWeight: 58,
  lateNormalUncommonWeight: 36,
  lateNormalRareWeight: 6,
  earlyEliteCommonWeight: 64,
  earlyEliteUncommonWeight: 36,
  earlyEliteRareWeight: 0,
  lateEliteCommonWeight: 24,
  lateEliteUncommonWeight: 48,
  lateEliteRareWeight: 28,
  bossCommonWeight: 10,
  bossUncommonWeight: 42,
  bossRareWeight: 48,
};

export const BOT_TRAINING_CONFIG: BotTrainingConfig = {
  populationSize: 10,
  eliteCount: 3,
  iterations: 8,
  matchesPerOpponent: 8,
  promotionMatchesPerOpponent: 12,
  initialSigma: 3.5,
  sigmaDecay: 0.84,
  minSigma: 0.45,
  defaultSearchDepth: 2,
  defaultBeamWidth: 10,
  heuristicBaselineBlend: 0.14,
  campaignTrainingRunsPerOpponent: 4,
  campaignPromotionRunsPerOpponent: 6,
  campaignScoreWeight: 0.11,
  promotionMinimumWinRateVsHeuristic: 0.54,
  promotionMinimumWinRateVsChampion: 0.5,
  promotionMinimumAverageHpEdge: 0.1,
  promotionMinimumCampaignScoreVsHeuristic: 24,
  promotionMinimumCampaignScoreVsChampion: 12,
  promotionMinimumBossReachRateVsHeuristic: 0,
  promotionMinimumBossReachRateVsChampion: 0,
};
